// config/movieSections.js
import {
  useLatestMovies, // ✅ Dùng hook thống nhất
  useVietnamMovies,
  useChinaMovies,
  useJapanMovies,
  useSeriesMovies,
  useSingleMovies,
  useAnimationMovies,
  useActionMovies,
  useHorrorMovies,
  useHistoryMovies,
  useDubbedMovies,
  useVoiceoverMovies,
  useVietsubMovies,
  transformLatestMovies, // ✅ Transform thống nhất
  transformVietnamMovies,
  transformChinaMovies,
  transformJapanMovies,
  transformSeriesMovies,
  transformSingleMovies,
  transformAnimationMovies,
  transformActionMovies,
  transformHorrorMovies,
  transformHistoryMovies,
  transformDubbedMovies,
  transformVietsubMovies,
  transformVoiceoverMovies,
} from "../hooks/useMovies";

export const MOVIE_SECTIONS = [
  // ✅ UNIFIED: Phim Mới Nhất dùng chung logic
  {
    title: "Phim Mới Nhất",
    emoji: "🔥",
    sectionKey: "latest",
    badgeColor: "bg-red-600",
    useDataHook: () => useLatestMovies(1), // ✅ Dùng hook thống nhất
    transformFunction: transformLatestMovies, // ✅ Transform thống nhất
    viewMoreLink: "/category/danh-sach/phim-moi",
  },
  {
    title: "Phim Việt Nam",
    emoji: "🇻🇳",
    sectionKey: "vietnam",
    badgeColor: "bg-red-600",
    useDataHook: () => useVietnamMovies(1),
    transformFunction: transformVietnamMovies,
    viewMoreLink: "/category/quoc-gia/viet-nam",
  },
  {
    title: "Phim Trung Quốc",
    emoji: "🇨🇳",
    sectionKey: "china",
    badgeColor: "bg-red-600",
    useDataHook: () => useChinaMovies(1),
    transformFunction: transformChinaMovies,
    viewMoreLink: "/category/quoc-gia/trung-quoc",
  },
  {
    title: "Phim Nhật Bản",
    emoji: "🇯🇵",
    sectionKey: "japan",
    badgeColor: "bg-red-600",
    useDataHook: () => useJapanMovies(1),
    transformFunction: transformJapanMovies,
    viewMoreLink: "/category/quoc-gia/nhat-ban",
  },
  {
    title: "Phim Bộ",
    emoji: "📺",
    sectionKey: "series",
    badgeColor: "bg-blue-600",
    useDataHook: () => useSeriesMovies(1),
    transformFunction: transformSeriesMovies,
    viewMoreLink: "/category/danh-sach/phim-bo",
  },
  {
    title: "Phim Lẻ",
    emoji: "🎬",
    sectionKey: "single",
    badgeColor: "bg-green-600",
    useDataHook: () => useSingleMovies(1),
    transformFunction: transformSingleMovies,
    viewMoreLink: "/category/danh-sach/phim-le",
  },
  {
    title: "Phim Hoạt Hình",
    emoji: "🎨",
    sectionKey: "animation",
    badgeColor: "bg-pink-600",
    useDataHook: () => useAnimationMovies(1),
    transformFunction: transformAnimationMovies,
    viewMoreLink: "/category/danh-sach/hoat-hinh",
  },
  {
    title: "Phim Thuyết Minh",
    emoji: "🎤",
    sectionKey: "dubbed",
    badgeColor: "bg-purple-600",
    useDataHook: () => useDubbedMovies(1),
    transformFunction: transformDubbedMovies,
    viewMoreLink: "/category/danh-sach/phim-thuyet-minh",
  },
  {
    title: "Phim Lồng Tiếng",
    emoji: "🗣️",
    sectionKey: "voiceover",
    badgeColor: "bg-indigo-600",
    useDataHook: () => useVoiceoverMovies(1),
    transformFunction: transformVoiceoverMovies,
    viewMoreLink: "/category/danh-sach/phim-long-tieng",
  },
  {
    title: "Phim Vietsub",
    emoji: "📝",
    sectionKey: "vietsub",
    badgeColor: "bg-cyan-600",
    useDataHook: () => useVietsubMovies(1),
    transformFunction: transformVietsubMovies,
    viewMoreLink: "/category/danh-sach/phim-vietsub",
  },
  {
    title: "Phim Hành Động",
    emoji: "💥",
    sectionKey: "action",
    badgeColor: "bg-orange-600",
    useDataHook: () => useActionMovies(1),
    transformFunction: transformActionMovies,
    viewMoreLink: "/category/the-loai/hanh-dong",
  },
  {
    title: "Phim Kinh Dị",
    emoji: "👻",
    sectionKey: "horror",
    badgeColor: "bg-gray-800",
    useDataHook: () => useHorrorMovies(1),
    transformFunction: transformHorrorMovies,
    viewMoreLink: "/category/the-loai/kinh-di",
  },
  {
    title: "Phim Cổ Trang",
    emoji: "🏛️",
    sectionKey: "history",
    badgeColor: "bg-amber-600",
    useDataHook: () => useHistoryMovies(1),
    transformFunction: transformHistoryMovies,
    viewMoreLink: "/category/the-loai/co-trang",
  },
];