// config/movieSections.js
import {
  useLatestMovies,
  useVietnamMovies,
  useChinaMovies,
  useJapanMovies,
  useSeriesMovies,
  useSingleMovies,
  useTVShows,
  useAnimationMovies,
  useActionMovies,
  useHorrorMovies,
  useHistoryMovies,
  useDubbedMovies,
  useVoiceoverMovies,
  useVietsubMovies,
  useCinemaMovies,
} from "../hooks/useMovies";

import {
  transformLatestMovies,
  transformVietnamMovies,
  transformChinaMovies,
  transformJapanMovies,
  transformSeriesMovies,
  transformSingleMovies,
  transformTVShows,
  transformAnimationMovies,
  transformActionMovies,
  transformHorrorMovies,
  transformHistoryMovies,
  transformDubbedMovies,
  transformVietsubMovies,
  transformVoiceoverMovies,
  transformCinemaMovies,
} from "../utils/transformFunctions";

export const MOVIE_SECTIONS = [
  {
    title: "Phim Mới Nhất",
    sectionKey: "latest",
    badgeColor: "bg-red-600",
    useDataHook: () => useLatestMovies(1),
    transformFunction: transformLatestMovies,
    viewMoreLink: "/category/danh-sach/phim-moi-cap-nhat",
  },
  {
    title: "Phim Việt Nam",
    sectionKey: "vietnam",
    badgeColor: "bg-red-600",
    useDataHook: () => useVietnamMovies(1),
    transformFunction: transformVietnamMovies,
    viewMoreLink: "/category/quoc-gia/viet-nam",
  },
  {
    title: "Phim Trung Quốc",
    sectionKey: "china",
    badgeColor: "bg-red-600",
    useDataHook: useChinaMovies,
    transformFunction: transformChinaMovies,
    viewMoreLink: "/category/quoc-gia/trung-quoc",
  },
  {
    title: "Phim Nhật Bản",
    sectionKey: "japan",
    badgeColor: "bg-red-600",
    useDataHook: useJapanMovies,
    transformFunction: transformJapanMovies,
    viewMoreLink: "/category/quoc-gia/nhat-ban",
  },
  {
    title: "Phim Bộ",
    sectionKey: "series",
    badgeColor: "bg-blue-600",
    useDataHook: useSeriesMovies,
    transformFunction: transformSeriesMovies,
    viewMoreLink: "/category/danh-sach/phim-bo",
  },
  {
    title: "Phim Lẻ",
    sectionKey: "single",
    badgeColor: "bg-green-600",
    useDataHook: useSingleMovies,
    transformFunction: transformSingleMovies,
    viewMoreLink: "/category/danh-sach/phim-le",
  },
  {
    title: "Phim Hoạt Hình",
    sectionKey: "animation",
    badgeColor: "bg-pink-600",
    useDataHook: useAnimationMovies,
    transformFunction: transformAnimationMovies,
    viewMoreLink: "/category/danh-sach/hoat-hinh",
  },
  {
    title: "Phim Chiếu Rạp",
    sectionKey: "cinema",
    badgeColor: "bg-yellow-600",
    useDataHook: useCinemaMovies,
    transformFunction: transformCinemaMovies,
    viewMoreLink: "/category/danh-sach/phim-chieu-rap",
  },
  {
    title: "Phim Thuyết Minh",
    sectionKey: "dubbed",
    badgeColor: "bg-purple-600",
    useDataHook: useDubbedMovies,
    transformFunction: transformDubbedMovies,
    viewMoreLink: "/category/danh-sach/phim-thuyet-minh",
  },
  {
    title: "Phim Lồng Tiếng",
    sectionKey: "voiceover",
    badgeColor: "bg-indigo-600",
    useDataHook: useVoiceoverMovies,
    transformFunction: transformVoiceoverMovies,
    viewMoreLink: "/category/danh-sach/phim-long-tieng",
  },
  {
    title: "Phim Vietsub",
    sectionKey: "vietsub",
    badgeColor: "bg-cyan-600",
    useDataHook: useVietsubMovies,
    transformFunction: transformVietsubMovies,
    viewMoreLink: "/category/danh-sach/phim-vietsub",
  },
  {
    title: "TV Shows",
    sectionKey: "tvshows",
    badgeColor: "bg-orange-600",
    useDataHook: useTVShows,
    transformFunction: transformTVShows,
    viewMoreLink: "/category/danh-sach/tv-shows",
  },
  {
    title: "Phim Kinh Dị",
    sectionKey: "horror",
    badgeColor: "bg-gray-800",
    useDataHook: useHorrorMovies,
    transformFunction: transformHorrorMovies,
    viewMoreLink: "/category/the-loai/kinh-di",
  },
  {
    title: "Phim Cổ Trang",
    sectionKey: "history",
    badgeColor: "bg-amber-600",
    useDataHook: useHistoryMovies,
    transformFunction: transformHistoryMovies,
    viewMoreLink: "/category/the-loai/co-trang",
  },
];
